server {
    include /etc/letsencrypt/options-ssl-nginx.conf;

    listen 443 ssl;
    listen 443 quic;
    server_name example.com;
    root /var/www/html/svh/frontend;

    http2 on;
    http3 on;
    quic_gso on;
    quic_retry on;

    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot

    add_header Alt-Svc 'h3=":443"; ma=86400';

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8007$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    include /etc/letsencrypt/options-ssl-nginx.conf;

    listen 443 ssl;
    listen 443 quic reuseport;
    server_name media.example.com;
    root /var/www/html/media;

    http2 on;
    http3 on;
    quic_gso on;
    quic_retry on;

    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    ssl_certificate /etc/letsencrypt/live/media.example.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/media.example.com/privkey.pem; # managed by Certbot

    add_header Alt-Svc 'h3=":443"; ma=86400';

    location / {
        try_files $uri =404;
    }

    location /video/subtitles/ {
        try_files $uri =404;

        add_header Access-Control-Allow-Origin *;
        add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS";
    }

    location /video/get/ {
        proxy_pass http://127.0.0.1:8007$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /videos/ {
        internal;
        alias /var/www/html/media/video/get/;
    }
}

